apiVersion: v1
kind: Service
metadata:
  name: loyalty
  namespace: food-delivery
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: loyalty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty
  template:
    metadata:
      labels:
        app: loyalty
    spec:
      containers:
        - name: loyalty
          image: adarrenleander/fooddelivery-loyalty:latest
          ports:
            - containerPort: 8081
