apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: food-delivery
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: notification
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: adarrenleander/fooddelivery-notification:latest
          ports:
            - containerPort: 8082
