apiVersion: v1
kind: Deployment
metadata:
  name: payment
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: food-delivery/payment:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: food-delivery
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      targetPort: 8084
  selector:
    app: payment
