apiVersion: v1
kind: Service
metadata:
  name: promotion
  namespace: food-delivery
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 8085
  selector:
    app: promotion
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promotion
  template:
    metadata:
      labels:
        app: promotion
    spec:
      containers:
        - name: promotion
          image: adarrenleander/fooddelivery-promotion:latest
          ports:
            - containerPort: 8085
