apiVersion: v1
kind: Service
metadata:
  name: tracking
  namespace: food-delivery
spec:
  type: LoadBalancer
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: tracking
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
        - name: tracking
          image: adarrenleander/fooddelivery-tracking:latest
          ports:
            - containerPort: 8087
