apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: food-delivery
spec:
  type: LoadBalancer
  ports:
    - port: 8088
      targetPort: 8088
  selector:
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: adarrenleander/fooddelivery-user:latest
          ports:
            - containerPort: 8088
